# Generated by Django 4.2 on 2023-04-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображения'),
        ),
    ]
